server:
  port: 8181
  servlet.context-path: /api

spring:
  jackson.serialization:
    fail-on-empty-beans: false
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER_ADDRESS:localhost}:${POSTGRES_DB_SERVER_PORT:5432}/Chinook
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  batch.job.enabled: false

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management.endpoint.health.show-details: ALWAYS
management.endpoint.health.probes.enabled: true
management.endpoints. web.exposure.include: "*"

logging:
  level:
    org.springframework: INFO
    com.personal.Chinook: INFO

jwt:
  secretKey: secret
  issuer: www.farukgenc.com
  expirationMinute: 10

swagger:
  contact-name: Obvinsev Aleksey
  contact-mail: Obvintsev.Aleksey@yandex.ru
  app-name: Rest-api Spring Boot starter
  app-description: "Rest-api Spring Boot Boilerplate starter.\n This project includes : Spring Boot(3.3.1), Spring Data JPA, Spring Validation, Spring Security + JWT Token, PostgreSQL, Mapstruct, Lombok, Swagger (Open API).\n If you're hiring for AQA - [my telegramm contact](https://t.me/TommyBahama)."
  app-version: 3.3.1
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0